stages:

  status:
    cmd: python ./stages/00_status.py
    outs:
      - status.md5

  download:
    cmd: ./stages/01_download.sh
    deps:
      - ./stages/01_download.sh
    outs:
      - data

  build:
    cmd: python ./stages/02_build.py
    deps:
      - ./stages/02_build.py
      - data
    outs:
      - brick